renderers:
  - name: IrisDocRenderer
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      language: ts
      fmtConfig: fmt_ts.yaml
      exportFilePath: ../../src/index.ts
      templateUrl: https://github.com/AgoraIO/agora_doc_source/releases/download/master-build/rn_ng_json_template_en.json
