name: Setup
description: Setup Node.js and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Setup cocoapods
      if: ${{ runner.os == 'macOS' }}
      run: |
        gem install cocoapods -v 1.13.0
        gem install activesupport -v 7.0.8
      shell: bash

    - name: Cache dependencies
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          .yarn/install-state.gz
        key: ${{ runner.os }}-yarn-ng-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-yarn-ng-${{ hashFiles('**/yarn.lock') }}
          ${{ runner.os }}-yarn-ng-

    - name: Install dependencies
      env:
        POD_INSTALL: "0"
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --immutable
      shell: bash
