name: Doc
description: Generate comments.

inputs:
  github-token:
    description: >
      GITHUB_TOKEN (permissions contents: write and pull-requests: write) or a repo scoped Personal Access Token (PAT).
    required: true

  target-repo:
    description: Relative path under GITHUB_WORKSPACE to the repository.

runs:
  using: composite
  steps:
    - name: Generate comments
      uses: AgoraIO-Extensions/actions/.github/actions/doc@main
      with:
        github-token: ${{ inputs.github-token }}
        target-repo: ${{ inputs.target-repo }}
        config: fmt_config/fmt_ts.yaml
        language: ts
        base-template-url: https://github.com/AgoraIO/agora_doc_source/releases/download/master-build/rn_ng_json_template_en.json
        export-file-path: src/index.ts
