name: doc
description: Generate comments
inputs:
  target-path:
    description: The path to generate comments, if set, will skip clone & pr
    default: ""
  github-token:
    description: The github token
    required: true

runs:
  using: composite
  steps:
    - name: Generate comments
      uses: AgoraIO-Extensions/actions/.github/actions/doc@main
      with:
        target-repo: ${{ github.repository }}
        target-branch: ${{ github.ref_name }}
        target-path: ${{ inputs.target-path }}
        config: fmt_config/fmt_ts.yaml
        language: ts
        base-template-url: https://github.com/AgoraIO/agora_doc_source/releases/download/main/rn_ng_json_template_en.json
        export-file-path: src/index.ts
        github-token: ${{ inputs.github-token }}
