/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syan_agora_media_MediaPreProcessing */

#ifndef _Included_com_syan_agora_media_MediaPreProcessing
#define _Included_com_syan_agora_media_MediaPreProcessing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syan_agora_media_MediaPreProcessing
 * Method:    setCallback
 * Signature: (Lcom/syan/agora/media/MediaPreProcessing/ProgressCallback;)V
 */
JNIEXPORT void JNICALL Java_com_syan_agora_media_MediaPreProcessing_setCallback
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_syan_agora_media_MediaPreProcessing
 * Method:    setVideoCaptureByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_syan_agora_media_MediaPreProcessing_setVideoCaptureByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_syan_agora_media_MediaPreProcessing
 * Method:    setAudioRecordByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_syan_agora_media_MediaPreProcessing_setAudioRecordByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_syan_agora_media_MediaPreProcessing
 * Method:    setAudioPlayByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_syan_agora_media_MediaPreProcessing_setAudioPlayByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_syan_agora_media_MediaPreProcessing
 * Method:    setBeforeAudioMixByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_syan_agora_media_MediaPreProcessing_setBeforeAudioMixByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_syan_agora_media_MediaPreProcessing
 * Method:    setAudioMixByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_syan_agora_media_MediaPreProcessing_setAudioMixByteBuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_syan_agora_media_MediaPreProcessing
 * Method:    setVideoDecodeByteBuffer
 * Signature: (ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_com_syan_agora_media_MediaPreProcessing_setVideoDecodeByteBuffer
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_syan_agora_media_MediaPreProcessing
 * Method:    releasePoint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_syan_agora_media_MediaPreProcessing_releasePoint
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
