platform :ios, '9.0'
react_native_path = "../node_modules/react-native"
project "RCTAgora.xcodeproj"

target 'RCTAgora' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'react-native-agora', path: '../react-native-agora.podspec'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native'
end
