react_native_path = '../node_modules/react-native'
project 'simpleDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'simpleDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for simpleDemo
  pod 'react-native-agora', path: '../node_modules/react-native-agora'
  pod 'React', path: react_native_path
  pod 'yoga', path: "#{react_native_path}/ReactCommon/yoga"
  %w(DoubleConversion Folly glog).each do |lib_name|
    pod lib_name, podspec: "#{react_native_path}/third-party-podspecs/#{lib_name}.podspec"
  end
  target 'simpleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
