name: Build Android
description: Common steps for building Android app

inputs:
  new-arch:
    description: 'Whether to enable new architecture'
    required: true
    default: 'false'
  turbo-cache-dir:
    description: 'Turborepo cache directory'
    required: true
    default: '.turbo/android'
  build-task:
    description: 'The build task to run'
    required: true
    default: 'build:android'
  force-build:
    description: 'Whether to force the build'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Cache turborepo for Android
      uses: actions/cache@v3
      with:
        path: ${{ inputs.turbo-cache-dir }}
        key: ${{ runner.os }}-turborepo-android-${{ inputs.build-task }}-${{ inputs.new-arch }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-turborepo-android-${{ inputs.build-task }}-${{ inputs.new-arch }}-

    - name: Check turborepo cache for Android
      id: check-turbo-cache
      run: |
        TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run ${{ inputs.build-task }} --cache-dir="${{ inputs.turbo-cache-dir }}" --dry=json)).tasks.find(t => t.task === '${{ inputs.build-task }}').cache.status")

        if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
          echo "turbo_cache_hit=1" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Install JDK
      if: env.turbo_cache_hit != 1
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Finalize Android SDK
      if: env.turbo_cache_hit != 1
      run: |
        /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"
      shell: bash

    - name: Cache Gradle
      if: env.turbo_cache_hit != 1
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/wrapper
          ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ inputs.new-arch }}-${{ hashFiles('example/android/gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-${{ inputs.new-arch }}-

    - name: Modify APP ID
      run: |
        sed "s/localAppId = '\(.*\)'/localAppId = '${{ secrets.APP_ID }}'/g" agora.config.ts > tmp
        mv tmp agora.config.ts
      working-directory: example/src/config
      shell: bash

    - name: Build example for Android
      run: |
        yarn turbo run ${{ inputs.build-task }} --cache-dir="${{ inputs.turbo-cache-dir }}" ${{ inputs.force-build == 'true' && '--force=true' || '' }}
      shell: bash
