/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IAudioEncodedFrameObserver = t.iface([], {
  "onRecordAudioEncodedFrame": t.opt(t.func(t.iface([], {
    "frameBuffer": "Uint8Array",
    "audioEncodedFrameInfo": "EncodedAudioFrameInfo",
  }), t.param("length", "number"))),
  "onPlaybackAudioEncodedFrame": t.opt(t.func(t.iface([], {
    "frameBuffer": "Uint8Array",
    "audioEncodedFrameInfo": "EncodedAudioFrameInfo",
  }), t.param("length", "number"))),
  "onMixedAudioEncodedFrame": t.opt(t.func(t.iface([], {
    "frameBuffer": "Uint8Array",
    "audioEncodedFrameInfo": "EncodedAudioFrameInfo",
  }), t.param("length", "number"))),
});

const exportedTypeSuite: t.ITypeSuite = {
  IAudioEncodedFrameObserver,
};
export default exportedTypeSuite;
