/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from 'ts-interface-checker';
// tslint:disable:object-literal-key-quotes

export const IAudioEncodedFrameObserver = t.iface([], {
  onRecordAudioEncodedFrame: t.opt(
    t.func(
      'void',
      t.param('frameBuffer', 'Uint8Array'),
      t.param('length', 'number'),
      t.param('audioEncodedFrameInfo', 'EncodedAudioFrameInfo')
    )
  ),
  onPlaybackAudioEncodedFrame: t.opt(
    t.func(
      'void',
      t.param('frameBuffer', 'Uint8Array'),
      t.param('length', 'number'),
      t.param('audioEncodedFrameInfo', 'EncodedAudioFrameInfo')
    )
  ),
  onMixedAudioEncodedFrame: t.opt(
    t.func(
      'void',
      t.param('frameBuffer', 'Uint8Array'),
      t.param('length', 'number'),
      t.param('audioEncodedFrameInfo', 'EncodedAudioFrameInfo')
    )
  ),
});

const exportedTypeSuite: t.ITypeSuite = {
  IAudioEncodedFrameObserver,
};
export default exportedTypeSuite;
