/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes



const exportedTypeSuite: t.ITypeSuite = {
};
export default exportedTypeSuite;
