/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const AgoraPipStateChangedObserver = t.iface([], {
  "onPipStateChanged": t.func("void", t.param("state", "AgoraPipState"), t.param("error", t.union("string", "null"))),
});

const exportedTypeSuite: t.ITypeSuite = {
  AgoraPipStateChangedObserver,
};
export default exportedTypeSuite;
