name: Update dependencies

on:
  workflow_dispatch:
    inputs:
      dependencies-content:
        description: The content of dependencies
        required: true
        type: string

jobs:
  update-dependencies:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Get dependencies
        id: dep
        uses: AgoraIO-Extensions/actions/.github/actions/dep@main
        with:
          dependencies-content: ${{ inputs.dependencies-content }}

      - name: Update dependencies
        run: |
          sh scripts/dep.sh ${{ steps.dep.outputs.matches }}

      - name: Generate code and comment by terra
        uses: AgoraIO-Extensions/actions/.github/actions/generate@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          generate-code: true
          generate-comment: true
          generate-code-command: |
            sh generate-prepare.sh
            sh generate-code.sh
          generate-comment-command: |
            sh generate-comment.sh

      - name: Update example
        run: |
          rm -rf examples/expo/ios/Podfile.lock
          yarn pod-install examples/expo/ios

      - name: Create pull request
        uses: AgoraIO-Extensions/actions/.github/actions/pr@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          target-repo: ${{ github.workspace }}
          target-branch: ${{ github.ref_name }}
          target-branch-name-surffix: dep-update
          pull-request-title: |
            [AUTO] Update dependencies
          pull-request-body: |
            Dependencies content:

            ${{ steps.dep.outputs.matches }}
